apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    name: api-pod
    app: slim-project
spec:
  containers:
  - name: app
    image: gcr.io/divine-camera-344312/slim-project
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    name: api-service
    app: slim-project
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 80
  selector:
    name: api-pod
    app: slim-project